-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  name_he text,
  category text,
  image text,
  description text,
  description_he text,
  is_hidden boolean default false
);

-- Create messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  phone text,
  message text,
  is_read boolean default false
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;
alter table public.messages enable row level security;

-- Create policies for products (Public read, Authenticated write)
create policy "Public products are viewable by everyone."
  on products for select
  using ( true );

create policy "Users can insert new products."
  on products for insert
  with check ( true ); 

create policy "Users can update their own products."
  on products for update
  using ( true );

create policy "Users can delete their own products."
  on products for delete
  using ( true );

-- Create policies for messages (Public insert, Authenticated read/update)
create policy "Public can insert messages"
  on messages for insert
  with check ( true );

create policy "Authenticated users can view messages"
  on messages for select
  using ( true );

create policy "Authenticated users can update messages"
  on messages for update
  using ( true );

create policy "Authenticated users can delete messages"
  on messages for delete
  using ( true );

-- Create storage bucket for product-images if it doesn't exist
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Storage policies
create policy "Give public access to product-images"
  on storage.objects for select
  using ( bucket_id = 'product-images' );

create policy "Enable upload for everyone"
  on storage.objects for insert
  with check ( bucket_id = 'product-images' );

