'use client';

import { useEffect, useState } from 'react';

export default function DiagPage() {
  const [envStatus, setEnvStatus] = useState(null);

  useEffect(() => {
    // Read env vars immediately on mount
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

    setEnvStatus({
      url: {
        value: url,
        exists: !!url,
        length: url ? url.length : 0,
      },
      key: {
        exists: !!key,
        length: key ? key.length : 0,
        prefix: key ? key.substring(0, 5) + '...' : 'N/A'
      },
      nodeEnv: process.env.NODE_ENV
    });
  }, []);

  if (!envStatus) return <div className="p-10 text-xl font-mono">Loading diagnostic...</div>;

  return (
    <div className="min-h-screen p-10 font-mono bg-black text-green-400">
      <h1 className="text-3xl mb-8 border-b border-green-700 pb-4">Vercel Env Diagnostic</h1>
      
      <div className="grid gap-6 max-w-2xl">
        {/* URL CHECK */}
        <div className="border border-green-800 p-6 rounded bg-gray-900">
          <h2 className="text-xl mb-4 text-white">1. SUPABASE URL</h2>
          <div className="flex justify-between mb-2">
            <span>Status:</span>
            <span className={envStatus.url.exists ? 'text-green-500 font-bold' : 'text-red-500 font-bold'}>
              {envStatus.url.exists ? 'PRESENT ✅' : 'MISSING ❌'}
            </span>
          </div>
          <div className="flex justify-between">
            <span>Length:</span>
            <span>{envStatus.url.length} characters</span>
          </div>
          <div className="mt-4 p-2 bg-black rounded break-all border border-green-900 text-sm">
            {envStatus.url.value || '(empty)'}
          </div>
        </div>

        {/* KEY CHECK */}
        <div className="border border-green-800 p-6 rounded bg-gray-900">
          <h2 className="text-xl mb-4 text-white">2. SUPABASE KEY (ANON)</h2>
          <div className="flex justify-between mb-2">
            <span>Status:</span>
            <span className={envStatus.key.exists ? 'text-green-500 font-bold' : 'text-red-500 font-bold'}>
              {envStatus.key.exists ? 'PRESENT ✅' : 'MISSING ❌'}
            </span>
          </div>
          <div className="flex justify-between">
            <span>Length:</span>
            <span>{envStatus.key.length} characters</span>
          </div>
          <div className="mt-4 p-2 bg-black rounded break-all border border-green-900 text-sm">
             Starts with: {envStatus.key.prefix}
          </div>
        </div>

        {/* SYSTEM CHECK */}
         <div className="border border-green-800 p-6 rounded bg-gray-900">
          <h2 className="text-xl mb-4 text-white">3. SYSTEM</h2>
           <div className="flex justify-between">
            <span>Environment:</span>
            <span className="text-yellow-400">{envStatus.nodeEnv}</span>
          </div>
        </div>

      </div>
      
      <div className="mt-10 text-gray-500 text-sm">
        Generated by Antigravity IDE
      </div>
    </div>
  );
}
